### ISSUE TITLE
🚀 Roadmap

### ISSUE THREAD

**Issue by TheBusyBiscuit** [baked-libs/dough#19]
# 📖 History
This project has just started out. Well kind of...
The original project's history actually dates all the way back to 2015, being first released as [CS-CoreLib](https://github.com/TheBusyBiscuit/CS-CoreLib).
In 2019, this library was re-established as [CS-CoreLib 2](https://github.com/TheBusyBiscuit/CS-CoreLib2).
Now in 2021, the library is being rewritten and re-furnished as **dough**.

**Dough** is a multi-module Maven project which provides various utilities the average Spigot and Paper plugin developer may need. It's open-sourced and released under the permissive MIT License.
Contributions are very much welcome!

However, there are still lots of things to do, to fix and to clean up before we will have our first proper 1.0 release.
This issue serves as the starting ground and we will utilise GitHub's new sub-issue functionality here to create child issues off of this roadmap.

## 👐🏻 The team
The current maintainers of dough:
* @TheBusyBiscuit 
* @md5sha256 
* @WalshyDev 

## 📝 The big TODO list
This list is ordered by priority, this does not necessarily mean that it needs to be fulfilled in sequence.

* [x] Get a logo for dough and the @baked-libs organization. (Thanks @IAmSorryArt <3)
* [x] Convert dough to a multi-module Maven module
* [x] Set up sonarcloud
* [x] Unify all annotations using `javax.annotations`
* [ ] Create a decent `README.md` file
* [ ] Implement proper versioning tools (semver and prefixed versions) for `dough-common`
* [ ] Properly implement `MinecraftVersion` (currently in `dough-reflection`, should be moved to `dough-common`)
* [ ] Implement proper usage of `DoughLogger` wherever an `Exception` may be thrown
* [ ] Get `dough-data` compilation-ready
* [ ] Get `dough-inventories` compilation-ready
* [ ] Fix `dough-tags`
* [ ] De-clutter and re-organize `dough-recipes`
* [ ] Rewrite the chat input logic for `dough-chat`
* [ ] Improve upon `dough-inventories` and perhaps rewrite that completely
* [ ] Update to Java 16 (Tracked in #17)
* [ ] Get rid of all the [technical debt](https://sonarcloud.io/dashboard?id=baked-libs_dough)
* [ ] Achieve 100% test coverage for `dough-common`
* [ ] Start to add Unit Tests for the remaining modules
* [ ] Publish `dough` to a maven repository, perhaps even maven-central? :eyes:
* [ ] Integrate `dough` into Slimefun
